'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {addServer,decode,encode}=require('../src/nbt.cjs');const {validate,update,recover,inspect}=require('../src/updater.cjs');const {safeRelative,safeTarget,json,writeJson}=require('../src/io.cjs');const mc=require('../src/minecraft.cjs');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'pepa test ñ '));t.after(()=>fs.rm(root,{recursive:true,force:true}));for(const p of ['home','game','bundle/objects'])await fs.mkdir(path.join(root,p),{recursive:true});return {root,home:path.join(root,'home'),game:path.join(root,'game'),bundled:path.join(root,'bundle')};}
function entry(name,data,policy='managed'){return {path:name,size:Buffer.byteLength(data),sha256:crypto.createHash('sha256').update(data).digest('hex'),policy};}
function manifest(files,revision=1){return {schema:1,id:'pepaworld-3',version:'3.0.'+revision,revision,minecraft:'1.21.1',neoforge:'21.1.250',files};}
async function object(f,e,data){await fs.writeFile(path.join(f.bundled,'objects',e.sha256),data);}
test('NBT: añade sin duplicar y conserva etiquetas/servidores desconocidos',()=>{const old={type:10,name:'',value:[{type:8,name:'extra',value:'ñá 🎮\u0000'},{type:9,name:'servers',value:{type:10,items:[[{type:8,name:'name',value:'Otro servidor'},{type:8,name:'ip',value:'localhost:25565'},{type:1,name:'acceptTextures',value:Buffer.from([0])}]]}}]};const bytes=addServer(encode(old));assert.deepEqual(addServer(bytes),bytes);const parsed=decode(bytes);assert.equal(parsed.value[0].value,'ñá 🎮\u0000');assert.equal(parsed.value[1].value.items.length,2);assert.equal(parsed.value[1].value.items[0][0].value,'Otro servidor');assert.throws(()=>decode(Buffer.from([10,0])));});
test('NBT: lee también gzip',()=>{const b=addServer();assert.deepEqual(addServer(require('node:zlib').gzipSync(b)),b);});
test('Manifest: rechaza escapes, duplicados Windows y carpetas ajenas',()=>{for(const name of ['../mods/a','mods/../../a','C:/a','mods\\a','mods/CON.jar','mods/a:secret','mods/a.','/mods/a'])assert.throws(()=>safeRelative(name));assert.throws(()=>validate(manifest([entry('launcher_profiles.json','x')])));assert.throws(()=>validate(manifest([entry('mods/A.jar','a'),entry('mods/a.jar','a')])));assert.throws(()=>validate({...manifest([]),neoforge:'999'}));});
test('Actualización incremental: instala, repara, borra solo gestionados y conserva opciones',async t=>{const f=await fixture(t),a=entry('mods/a.jar','aaa'),b=entry('config/b.toml','b');await object(f,a,'aaa');await object(f,b,'b');const m=manifest([a,b]);assert.equal((await update({...f,manifest:m})).changed,2);assert.equal((await update({...f,manifest:m})).changed,0);await fs.writeFile(path.join(f.game,'options.txt'),'mis controles');await fs.writeFile(path.join(f.game,'mods','extra.jar'),'mio');await fs.writeFile(path.join(f.game,'mods/a.jar'),'bad');assert.equal((await inspect(f.home,f.game,m)).changed,1);assert.equal((await update({...f,manifest:m})).changed,1);assert.equal((await update({...f,manifest:manifest([b],2)})).removed,1);assert.equal(await fs.readFile(path.join(f.game,'mods/extra.jar'),'utf8'),'mio');assert.equal(await fs.readFile(path.join(f.game,'options.txt'),'utf8'),'mis controles');await assert.rejects(update({...f,manifest:m}),/anterior/);});
test('Fallo de integridad no modifica la instancia',async t=>{const f=await fixture(t),a=entry('mods/a.jar','correcto');await object(f,a,'corrupto');await assert.rejects(update({...f,manifest:manifest([a])}),/Falta/);await assert.rejects(fs.stat(path.join(f.game,'mods/a.jar')));});
test('Fallo durante aplicación revierte los archivos y el estado',async t=>{const f=await fixture(t),a=entry('mods/a.jar','original');await object(f,a,'original');await update({...f,manifest:manifest([a])});const b=entry('mods/a.jar','nuevo'),c=entry('mods/b.jar','b');await object(f,b,'nuevo');await object(f,c,'b');await assert.rejects(update({...f,manifest:manifest([b,c],2),failAfter:1}),/simulado/);assert.equal(await fs.readFile(path.join(f.game,'mods/a.jar'),'utf8'),'original');assert.equal((await json(path.join(f.home,'installed.json'))).revision,1);await assert.rejects(fs.stat(path.join(f.game,'mods/b.jar')));});
test('Recupera una transacción interrumpida al reiniciar',async t=>{const f=await fixture(t);await fs.mkdir(path.join(f.home,'backups','test','mods'),{recursive:true});await fs.mkdir(path.join(f.game,'mods'));await fs.writeFile(path.join(f.home,'backups/test/mods/a.jar'),'old');await fs.writeFile(path.join(f.game,'mods/a.jar'),'new');await writeJson(path.join(f.home,'transaction.json'),{id:'test',game:path.resolve(f.game),oldState:manifest([],1),ops:[{path:'mods/a.jar',hadOriginal:true}]});await recover(f.home,f.game);assert.equal(await fs.readFile(path.join(f.game,'mods/a.jar'),'utf8'),'old');});
test('No sigue enlaces fuera de la instancia',async t=>{if(process.platform==='win32')return t.skip('Enlaces requieren permisos particulares en Windows');const f=await fixture(t);await fs.symlink(f.home,path.join(f.game,'mods'));await assert.rejects(safeTarget(f.game,'mods/a.jar'),/Enlace/);});
test('Política seed conserva las preferencias locales',async t=>{const f=await fixture(t),a=entry('config/a.toml','default','seed');await object(f,a,'default');await update({...f,manifest:manifest([a])});await fs.writeFile(path.join(f.game,a.path),'personal');await update({...f,manifest:manifest([a],2)});assert.equal(await fs.readFile(path.join(f.game,a.path),'utf8'),'personal');});
test('Perfiles: conserva cuentas, selección y perfiles existentes; rutas con espacios',async t=>{const f=await fixture(t),profiles={profiles:{otro:{name:'Otra instalación',lastVersionId:'1.20.1'}},selectedUser:{account:'NO_CAMBIAR'},authenticationDatabase:{data:'NO_CAMBIAR'},selectedProfile:'otro'};await writeJson(path.join(f.root,'launcher_profiles.json'),profiles);await mc.profile(f.root,f.game,'C:\\Program Files\\Java\\bin\\java.exe',6);const d=await json(path.join(f.root,'launcher_profiles.json'));assert.deepEqual(d.authenticationDatabase,profiles.authenticationDatabase);assert.deepEqual(d.selectedUser,profiles.selectedUser);assert.equal(d.selectedProfile,'otro');assert.deepEqual(d.profiles.otro,profiles.profiles.otro);assert.equal(d.profiles['pepaworld-3'].gameDir,f.game);await mc.server(f.game);await mc.server(f.game);assert.equal(decode(await fs.readFile(path.join(f.game,'servers.dat'))).value[0].value.items.length,1);});
test('Rechaza reutilizar una revisión con contenido distinto',async t=>{const f=await fixture(t),a=entry('mods/a.jar','a');await object(f,a,'a');await update({...f,manifest:manifest([a])});await assert.rejects(update({...f,manifest:manifest([])}),/archivos distintos/);});

test('NBT: admite lista vacía con tipo End de Minecraft',()=>{const b=encode({type:10,name:'',value:[{type:9,name:'servers',value:{type:0,items:[]}}]});assert.equal(decode(addServer(b)).value[0].value.items.length,1);});
