'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {chooseRegisteredApps,resolveOfficial,launchOfficial}=require('../src/launcher.cjs');
const launcher={Name:'Minecraft Launcher',AppID:'Microsoft.4297127D64EC6_8wekyb3d8bbwe!Minecraft'};
const bedrock={Name:'Minecraft for Windows',AppID:'Microsoft.MinecraftUWP_8wekyb3d8bbwe!App'};
function deps(rows=[]){return {platform:'win32',env:{SystemRoot:'C:\\Windows'},exists:async()=>false,run:async()=>JSON.stringify(rows)};}
test('Con Java Launcher y Bedrock instalados, selecciona únicamente el Launcher',()=>{assert.equal(chooseRegisteredApps([bedrock,launcher]),launcher.AppID);assert.equal(chooseRegisteredApps([bedrock]),null);assert.equal(chooseRegisteredApps([{...bedrock,Name:'Minecraft Launcher'}]),null);});
test('Microsoft Store: abre el AppID registrado con AppsFolder y sin protocolo Bedrock',async()=>{const calls=[];await launchOfficial('',{...deps([bedrock,launcher]),start:async(...args)=>calls.push(args)});assert.deepEqual(calls,[['C:\\Windows\\explorer.exe',['shell:AppsFolder\\'+launcher.AppID]]]);});
test('Launcher clásico: respeta su ejecutable y no consulta Microsoft Store',async()=>{const expected='C:\\Program Files (x86)\\Minecraft Launcher\\MinecraftLauncher.exe';const target=await resolveOfficial('',{...deps(),exists:async p=>p===expected,run:async()=>{throw Error('No debe ejecutarse');}});assert.deepEqual(target,{kind:'executable',file:expected});});
test('Solo Bedrock o detección fallida: no abre nada y da instrucciones',async()=>{let calls=0;for(const run of [async()=>JSON.stringify([bedrock]),async()=>{throw Error('PowerShell no disponible');}])await assert.rejects(launchOfficial('',{...deps(),run,start:async()=>calls++}),/No encuentro Minecraft Launcher/);assert.equal(calls,0);});
test('Rechaza selección manual de Bedrock y conserva ejecutable Java con espacios',async()=>{await assert.rejects(resolveOfficial('C:\\Games\\Minecraft.Windows.exe',{...deps(),exists:async()=>true}),/Bedrock/);const file='C:\\Mis juegos\\MinecraftLauncher.exe',calls=[];await launchOfficial(file,{...deps(),exists:async()=>true,start:async(...args)=>calls.push(args)});assert.deepEqual(calls,[[file,[]]]);});
test('No ejecuta identificadores arbitrarios ni elige entre launchers ambiguos',()=>{assert.equal(chooseRegisteredApps([{Name:'Minecraft Launcher',AppID:'abc;evil.exe'}]),null);assert.equal(chooseRegisteredApps([{Name:'Minecraft Launcher',AppID:'abc'},{Name:'Minecraft Launcher',AppID:'xyz'}]),null);});
test('La integración de Minecraft no vuelve a usar minecraft://',()=>{const fs=require('node:fs'),path=require('node:path');for(const f of ['launcher.cjs','minecraft.cjs'])assert.ok(!fs.readFileSync(path.join(__dirname,'../src',f),'utf8').includes('minecraft://'));});
