'use strict';
const $=id=>document.getElementById(id);let state,busy=false;
function message(s){$('message').textContent=s;$('message').title=s;}
function render(s){state=s;const lu=s.launcherUpdate||{};$('launcherStatus').textContent=lu.error||(lu.available?'Nueva versión del launcher: '+lu.version:'Launcher '+s.appVersion+(lu.supported?' · Al día':''));$('updateLauncher').hidden=!lu.available;$('updateLauncher').disabled=busy;$('appVersion').textContent=s.appVersion?' · Launcher '+s.appVersion:'';$('version').textContent=s.installed||'Sin instalar';$('channel').textContent=s.available?'Disponible: '+s.available:'Paquete incluido';$('status').textContent=s.ready?'Tu instalación está preparada':'Prepara el juego para tu primera aventura';$('play').disabled=busy||!s.ready;$('update').textContent=s.installed?'↓  Actualizar':'↓  Instalar y preparar';
 const notes=[];if(!s.remoteConfigured)notes.push('Actualizaciones remotas pendientes de configurar por Puerto.');if(s.warnings?.length)notes.push('Paquete de prueba: consulta los avisos de compatibilidad del informe.');if(s.error)notes.push(s.error);$('notice').hidden=!notes.length;$('notice').textContent=notes.join(' ');
}
async function action(fn){if(busy)return;busy=true;document.body.classList.add('busy');for(const id of ['play','update','check','settingsOpen','folder','updateLauncher'])$(id).disabled=true;try{const result=await fn();if(result)render(result);}catch(e){message(e.message.replace(/^Error invoking remote method '[^']+': Error: /,''));}finally{busy=false;document.body.classList.remove('busy');for(const id of ['update','check','settingsOpen','folder','updateLauncher'])$(id).disabled=false;if(state)$('play').disabled=!state.ready;}}
$('check').onclick=()=>action(async()=>{message('Comprobando versiones…');const s=await window.pepa.check();message(s.error||(!s.remoteConfigured?'Se usará el paquete incluido.':'Comprobación terminada.'));return s;});
$('update').onclick=()=>action(()=>window.pepa.update());$('play').onclick=()=>action(()=>window.pepa.play());$('folder').onclick=()=>action(()=>window.pepa.folder());
$('settingsOpen').onclick=()=>{const s=state.settings;for(const name of ['minecraftDir','launcherMode','launcherPath','manifestUrl'])$(name).value=s[name];$('memory').value=s.memoryGB;$('launcherArgs').value=JSON.stringify(s.launcherArgs);$('instancePath').textContent='Instancia: '+s.gameDir;$('externalSettings').hidden=s.launcherMode!=='external';$('settingsError').textContent='';$('settings').showModal();};
$('settingsClose').onclick=()=>{if(!busy)$('settings').close();};$('launcherMode').onchange=()=>{$('externalSettings').hidden=$('launcherMode').value!=='external';};
$('browseMinecraft').onclick=async()=>{try{const p=await window.pepa.choose('minecraft');if(p)$('minecraftDir').value=p;}catch(e){$('settingsError').textContent=e.message;}};
$('browseLauncher').onclick=async()=>{try{const p=await window.pepa.choose('launcher');if(p)$('launcherPath').value=p;}catch(e){$('settingsError').textContent=e.message;}};
$('settingsForm').onsubmit=async e=>{e.preventDefault();if(busy)return;try{const s={};for(const name of ['minecraftDir','launcherMode','launcherPath','manifestUrl'])s[name]=$(name).value.trim();s.launcherArgs=JSON.parse($('launcherArgs').value);s.memoryGB=Number($('memory').value);render(await window.pepa.saveSettings(s));$('settings').close();message('Ajustes guardados. Pulsa Actualizar para preparar el perfil.');}catch(err){$('settingsError').textContent=err.message;}};
window.pepa.onProgress(message);action(()=>window.pepa.check());

$('updateLauncher').onclick=()=>action(()=>window.pepa.updateLauncher());
